# Server settings
server:
    port: "8080"

logging:
    level:
        com.jc: DEBUG

spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    # DATASOURCE druid connetion pool
    datasource:
        name: test
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.36.10:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&idleConnectionTestPeriod=120&preferredTestQuery=select now()&allowMultiQueries=true
        username: jc_test
        password: jc123456!
        initialSize: 5
        minIdle: 1
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat
    mvc:
        view:
            prefix: /templates/
            suffix: .html
    # redis
    redis:
        host: 127.0.0.1
        port: 6379
        database: 1
        password:
        timeout: 120000
        pool:
            #池中可借的最大数
            max-active: 120
            #允许池中空闲的最大连接数
            max-idle: 30
            #获取连接最大等待时间（毫秒）
            max-wait: 12000
            #允许池中空闲的最小连接数
            min-idle: 0